/**
 * `periodKey(worker, period)` in TypeScript — the map key the contract uses
 * for `approvedHours`, `paidFor` and `contributionOk`.
 *
 * WHY THIS IS REIMPLEMENTED RATHER THAN IMPORTED
 *
 * `payroll.compact` exports `dappKey` and `sealRate`, so the api can call
 * them through the generated `pureCircuits`. It does NOT export `periodKey`:
 * the circuits that need it compute it internally, so nothing forced the
 * export. That leaves reading those three maps from outside the contract
 * with no key to look up.
 *
 * Reimplementing a hash is exactly the thing `sealRate`'s doc comment warns
 * against — "getting the byte encoding subtly wrong would break acceptHire
 * forever". Two things make it safe here where it would not be there:
 *
 *  1. This is a *read*. A wrong key finds nothing; it cannot write a bad
 *     value or brick a worker's employment the way a wrong commitment would.
 *  2. It is checkable against a real chain, and is checked. `demo-lifecycle.ts`
 *     approves a period and then asserts `getEmploymentRecord` reports it —
 *     which it can only do if the key computed here matches the one the
 *     contract wrote under. A wrong encoding fails that run loudly instead of
 *     quietly returning "this worker has no history".
 *
 * The construction is copied from the generated bindings rather than from
 * the Compact source, so the byte-level details are the compiler's, not
 * mine. `packages/contract/src/managed/contract/index.js`, `_periodKey_0`:
 *
 *     _persistentHash_0([<"nightshift:period:" padded to 32 bytes>,
 *                        worker_0,
 *                        convertFieldToBytes(32, period_0, ...)])
 *
 * with `_descriptor_5 = new CompactTypeVector(3, new CompactTypeBytes(32))`.
 *
 * The right long-term fix is one word — `export pure circuit periodKey` in
 * payroll.compact — after which this file becomes a thin re-export. It is
 * not done here only because it needs the Compact toolchain (WSL) and a
 * recompile, and this unblocks the apps today.
 */
import {
  CompactTypeBytes,
  CompactTypeVector,
  convertFieldToBytes,
  persistentHash,
} from '@midnight-ntwrk/compact-runtime';

/** `Vector<3, Bytes<32>>` — the type `periodKey` hashes. */
const VECTOR_OF_THREE_HASHES = new CompactTypeVector(3, new CompactTypeBytes(32));

/**
 * `pad(32, "nightshift:period:")` — Compact's `pad` is right-zero-fill, which
 * is what the generated byte array shows. A different separator from
 * `dappKey`'s is what stops a period key ever colliding with an identity key.
 */
const PERIOD_DOMAIN_SEPARATOR = (() => {
  const padded = new Uint8Array(32);
  padded.set(new TextEncoder().encode('nightshift:period:'));
  return padded;
})();

/**
 * The key under which the contract filed one worker's one period.
 *
 * @param workerBytes the worker's 32-byte `dappKey`
 * @param period the period as the contract sees it — a `Uint<32>`, so the
 *   output of `periodToUint32`, never a `"YYYY-MM"` string.
 */
export function periodKey(workerBytes: Uint8Array, period: bigint): Uint8Array {
  return persistentHash(VECTOR_OF_THREE_HASHES, [
    PERIOD_DOMAIN_SEPARATOR,
    workerBytes,
    convertFieldToBytes(32, period, 'periodKey'),
  ]);
}
